# Generated by Django 3.2.19 on 2023-06-15 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_likes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='posts.post')),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('owner', 'post')},
            },
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
