# Generated by Django 3.2.19 on 2023-06-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_likes', '0001_initial'),
    ]

    operations = [
    ]
