# Generated by Django 3.2.19 on 2023-05-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_on']},
        ),
    ]
