# Generated by Django 3.2.19 on 2023-05-28 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
        ('comment_likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlikes',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='commentlikes',
            unique_together={('owner', 'comment', 'content')},
        ),
    ]
