# Generated by Django 3.2.19 on 2023-05-28 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment_likes', '0002_auto_20230528_1627'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlikes',
            unique_together={('owner', 'comment')},
        ),
        migrations.RemoveField(
            model_name='commentlikes',
            name='content',
        ),
    ]
